const DEFAULT_PLAN=[
{day:'周一',short:'一',title:'胸部 + 三头',rest:false,optional:false,minutes:55,exercises:[{icon:'🏋️',name:'杠铃卧推',sets:4,reps:10,weight:60,tip:'肩胛骨向后下方收紧，双脚踩稳，控制下放。'},{icon:'💪',name:'上斜哑铃卧推',sets:4,reps:12,weight:20,tip:'保持小角度上斜，手腕中立，控制离心。'},{icon:'⭕',name:'绳索夹胸',sets:3,reps:15,weight:15,tip:'胸部主动发力，避免身体摆动。'},{icon:'⚡',name:'绳索下压',sets:4,reps:12,weight:20,tip:'大臂贴近身体，固定肘关节。'}]},
{day:'周二',short:'二',title:'休息恢复',rest:true,optional:false,minutes:0,exercises:[]},
{day:'周三',short:'三',title:'背部 + 二头',rest:false,optional:false,minutes:60,exercises:[{icon:'🧗',name:'高位下拉',sets:4,reps:12,weight:40,tip:'先下沉肩胛，再将横杆拉向上胸。'},{icon:'🏋️',name:'坐姿划船',sets:4,reps:12,weight:40,tip:'保持脊柱中立，末端夹紧肩胛。'},{icon:'🔩',name:'单臂哑铃划船',sets:3,reps:10,weight:18,tip:'核心收紧，向髋部方向拉。'},{icon:'💪',name:'杠铃弯举',sets:4,reps:10,weight:20,tip:'避免身体摇摆，控制下放。'}]},
{day:'周四',short:'四',title:'休息恢复',rest:true,optional:false,minutes:0,exercises:[]},
{day:'周五',short:'五',title:'腿部 + 肩部',rest:false,optional:false,minutes:65,exercises:[{icon:'🦵',name:'深蹲',sets:4,reps:8,weight:60,tip:'核心收紧，膝盖方向与脚尖一致。'},{icon:'🏋️',name:'罗马尼亚硬拉',sets:4,reps:10,weight:50,tip:'髋部向后，背部保持中立。'},{icon:'⬆️',name:'哑铃肩推',sets:4,reps:10,weight:15,tip:'核心收紧，推举路径稳定。'},{icon:'↔️',name:'哑铃侧平举',sets:4,reps:15,weight:7.5,tip:'用较轻重量控制，避免耸肩。'}]},
{day:'周六',short:'六',title:'可选：有氧 + 核心',rest:false,optional:true,minutes:35,exercises:[{icon:'🏃',name:'跑步 / 椭圆机',sets:1,reps:25,unit:'分钟',weight:0,tip:'中等强度即可，不需要每次高强度。'},{icon:'🧱',name:'平板支撑',sets:3,reps:60,unit:'秒',weight:0,tip:'保持躯干稳定，避免塌腰。'}]},
{day:'周日',short:'日',title:'完全休息',rest:true,optional:false,minutes:0,exercises:[]}
];
const KEY='weekly-fit-v5',OLD_KEYS=['weekly-fit-v4','weekly-fit-v3'];const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const clone=x=>JSON.parse(JSON.stringify(x));
const now=new Date();let selected=now.getDay()===0?6:now.getDay()-1,activeExercise=null,editingDay=null,calendarCursor=new Date(now.getFullYear(),now.getMonth(),1),sessionTimer=null,restTimer=null,restRemaining=90,restInitial=90;
function defaults(){return{days:{},history:[],weights:[],profile:{name:'Eggo',goal:'增肌塑形',height:'',targetWeight:'',weeklyTarget:3,restSeconds:90},session:null,plan:clone(DEFAULT_PLAN)}}
function loadState(){try{let raw=localStorage.getItem(KEY);if(!raw){for(const k of OLD_KEYS){raw=localStorage.getItem(k);if(raw)break}}const p=raw?JSON.parse(raw):{},d=defaults();return{...d,...p,profile:{...d.profile,...(p.profile||{})},plan:Array.isArray(p.plan)&&p.plan.length===7?p.plan:clone(DEFAULT_PLAN)}}catch{return defaults()}}
let state=loadState();let plan=state.plan;function save(){state.plan=plan;localStorage.setItem(KEY,JSON.stringify(state))}function isoDate(d=new Date()){const x=new Date(d.getTime()-d.getTimezoneOffset()*60000);return x.toISOString().slice(0,10)}
function weekKey(){const d=new Date(),day=(d.getDay()+6)%7;d.setHours(0,0,0,0);d.setDate(d.getDate()-day);return isoDate(d)}function dayKey(i){return`${weekKey()}-${i}`}function dayState(i){const k=dayKey(i);if(!state.days[k])state.days[k]={done:false,exercises:{}};return state.days[k]}
function showToast(t){const e=$('#toast');e.textContent=t;e.classList.add('show');clearTimeout(showToast.t);showToast.t=setTimeout(()=>e.classList.remove('show'),1600)}function formatClock(s){return`${String(Math.floor(s/60)).padStart(2,'0')}:${String(s%60).padStart(2,'0')}`}
function completedExerciseCount(ds){return Object.values(ds.exercises||{}).filter(x=>x?.done).length}function exerciseSummary(ex,d){if(d?.sets?.length){const l=d.sets.at(-1);return ex.unit?`${d.sets.length} 组 · ${l.reps} ${ex.unit}`:`${d.sets.length} 组 · ${l.weight||0} kg × ${l.reps}`}return ex.unit?`${ex.sets} 组 · ${ex.reps} ${ex.unit}`:`${ex.sets} 组 · ${ex.weight||0} kg × ${ex.reps}`}
function renderWeek(){const e=$('#weekStrip');e.innerHTML='';plan.forEach((p,i)=>{const s=dayState(i),b=document.createElement('button');b.className='day-chip'+(i===selected?' active':'')+(s.done?' done':'');b.innerHTML=`<span>${p.day}</span><strong>${p.short}</strong>`;b.onclick=()=>{selected=i;renderHome()};e.appendChild(b)})}
function renderWorkout(){const p=plan[selected],s=dayState(selected);$('#selectedDayName').textContent=p.day;$('#selectedWorkoutTitle').textContent=p.title;$('#selectedStatus').textContent=s.done?'已完成':p.rest?'休息日':p.optional?'可选':'未完成';$('#selectedStatus').className='pill'+(s.done?' done':'');const list=$('#workoutList');list.innerHTML='';if(p.rest||!p.exercises.length)list.innerHTML='<div class="guide-box">今天主要恢复。散步、轻拉伸或完全休息都可以。</div>';p.exercises.forEach((ex,i)=>{const d=s.exercises[i],b=document.createElement('button');b.className='exercise-card'+(d?.done?' completed':'');b.innerHTML=`<div class="exercise-icon">${ex.icon||'🏋️'}</div><div class="exercise-copy"><h4>${ex.name}</h4><p>${exerciseSummary(ex,d)}</p></div><div class="exercise-state">${d?.done?'✓':'›'}</div>`;b.onclick=()=>openExercise(selected,i);list.appendChild(b)});$('#completeDayBtn').style.display=p.rest?'none':'';$('#completeDayBtn').textContent=s.done?'取消今日完成':'完成今日训练';$('#completeDayBtn').className='primary-button'+(s.done?' secondary':'')}
function findNextWorkout(){const t=now.getDay()===0?6:now.getDay()-1;for(let n=0;n<7;n++){const i=(t+n)%7,p=plan[i];if(!p.rest&&!p.optional&&!dayState(i).done)return p}return null}
function renderStats(){const completed=plan.map((p,i)=>({p,s:dayState(i)})).filter(x=>!x.p.rest&&!x.p.optional&&x.s.done).length,target=+state.profile.weeklyTarget||3,pct=Math.min(100,Math.round(completed/target*100));$('#doneDays').textContent=completed;$('#targetDays').textContent=target;$('#progressPercent').textContent=pct+'%';$('#progressBar').style.width=pct+'%';$('#progressRing').style.background=`conic-gradient(var(--accent) ${pct*3.6}deg,rgba(255,255,255,.08) 0deg)`;$('#setsValue').textContent=plan.reduce((n,p,i)=>n+completedExerciseCount(dayState(i)),0);$('#minutesValue').textContent=state.history.filter(h=>h.date>=weekKey()).reduce((n,h)=>n+(h.minutes||0),0);$('#monthValue').textContent=state.history.filter(h=>h.date.slice(0,7)===isoDate().slice(0,7)).length;const next=findNextWorkout();$('#heroTip').textContent=completed>=target?'本周目标已完成。可选训练看体力，不做也没关系。':`本周还差 ${target-completed} 次。${next?`下一次：${next.day} · ${next.title}`:''}`;$('#quickWorkoutText').textContent=state.session?.active?'训练计时进行中':`${plan[selected].title} · ${plan[selected].minutes||0} 分钟`}
function renderSession(){const b=$('#liveSession');if(!state.session?.active){b.classList.add('hidden');clearInterval(sessionTimer);sessionTimer=null;return}b.classList.remove('hidden');$('#sessionTitle').textContent=state.session.title;$('#sessionStartedText').textContent=`开始于 ${new Date(state.session.startedAt).toLocaleTimeString('zh-CN',{hour:'2-digit',minute:'2-digit'})}`;tickSession();if(!sessionTimer)sessionTimer=setInterval(tickSession,1000)}function tickSession(){if(state.session?.active)$('#sessionClock').textContent=formatClock(Math.max(0,Math.floor((Date.now()-state.session.startedAt)/1000)))}
function startSession(){if(state.session?.active)return showToast('训练计时已经开始');if(plan[selected].rest)return showToast('今天是休息日');state.session={active:true,startedAt:Date.now(),day:selected,title:plan[selected].title};save();renderSession();renderStats();showToast('训练计时开始')}function finishSession(markDone=false){if(!state.session?.active)return;const mins=Math.max(1,Math.round((Date.now()-state.session.startedAt)/60000)),idx=state.session.day;state.session=null;save();renderSession();if(markDone){selected=idx;completeSelectedDay(false,mins)}else showToast(`本次训练 ${mins} 分钟`)}
function renderHome(){renderWeek();renderWorkout();renderStats();renderSession()}
function allCompletedSetsByName(name){const arr=[];state.history.forEach(h=>(h.details||[]).forEach(ex=>{if(ex.name===name)(ex.sets||[]).filter(s=>s.done!==false).forEach(s=>arr.push(s))}));return arr}function getPR(name){const sets=allCompletedSetsByName(name).filter(s=>+s.weight>0);if(!sets.length)return null;return sets.reduce((a,b)=>(+b.weight>+a.weight||(+b.weight===+a.weight&&+b.reps>+a.reps))?b:a)}
function openExercise(di,ei){activeExercise={dayIdx:di,exIdx:ei};const ex=plan[di].exercises[ei],d=dayState(di).exercises[ei]||{},pr=getPR(ex.name);$('#sheetExerciseName').textContent=ex.name;$('#exerciseGuide').innerHTML=`<strong>动作要点</strong><p>${ex.tip||'动作稳定，保持舒适范围，逐步增加负荷。'}</p>`;$('#exercisePr').innerHTML=pr?`历史 PR：<strong>${pr.weight} kg × ${pr.reps}</strong>`:'历史 PR：完成训练后开始记录';const rows=d.sets?.length?clone(d.sets):Array.from({length:ex.sets||1},()=>({weight:ex.weight||0,reps:ex.reps||10,done:false}));renderSetRows(rows,ex);openSheet('exerciseSheet')}
function renderSetRows(rows,ex){const t=$('#setTable');t.dataset.rows=JSON.stringify(rows);t.innerHTML='';rows.forEach((r,i)=>{const row=document.createElement('div');row.className='set-row'+(r.done?' done':'');row.innerHTML=`<span class="set-no">${i+1}</span>${ex.unit?'<span class="set-spacer">时长 / 次数</span>':`<label><small>KG</small><input class="set-weight" type="number" inputmode="decimal" step="0.5" value="${r.weight??0}"></label>`}<label><small>${ex.unit||'次数'}</small><input class="set-reps" type="number" inputmode="numeric" value="${r.reps??ex.reps}"></label><button class="set-check">${r.done?'✓':'○'}</button>`;row.querySelector('.set-check').onclick=()=>{updateRows();const a=JSON.parse(t.dataset.rows);a[i].done=!a[i].done;renderSetRows(a,ex);if(a[i].done&&!ex.unit)startRestTimer(+state.profile.restSeconds||90,true)};t.appendChild(row)})}
function updateRows(){const ex=plan[activeExercise.dayIdx].exercises[activeExercise.exIdx],old=JSON.parse($('#setTable').dataset.rows||'[]');const rows=$$('#setTable .set-row').map((r,i)=>({weight:ex.unit?0:+(r.querySelector('.set-weight')?.value||0),reps:+(r.querySelector('.set-reps')?.value||0),done:old[i]?.done||false}));$('#setTable').dataset.rows=JSON.stringify(rows);return rows}
function workoutDetails(p,s){return p.exercises.map((ex,i)=>({name:ex.name,sets:clone(s.exercises[i]?.sets||[])}))}function calcVolume(details=[]){return Math.round(details.reduce((n,e)=>n+(e.sets||[]).filter(s=>s.done!==false).reduce((a,s)=>a+(+s.weight||0)*(+s.reps||0),0),0))}
function completeSelectedDay(toggle=true,actualMinutes=null){const s=dayState(selected),p=plan[selected];if(p.rest)return;if(toggle&&s.done){s.done=false;save();renderAll();return showToast('已取消今日完成')}p.exercises.forEach((ex,i)=>{if(!s.exercises[i])s.exercises[i]={sets:Array.from({length:ex.sets||1},()=>({weight:ex.weight||0,reps:ex.reps||10,done:true}))};s.exercises[i].done=true;s.exercises[i].sets?.forEach(x=>x.done=true)});s.done=true;const details=workoutDetails(p,s),sets=details.reduce((n,e)=>n+e.sets.filter(x=>x.done).length,0),minutes=actualMinutes||p.minutes||30,date=isoDate(),volume=calcVolume(details),existing=state.history.find(h=>h.date===date&&h.day===selected);const payload={id:existing?.id||Date.now(),date,day:selected,title:p.title,minutes,exercises:p.exercises.length,sets,optional:p.optional,volume,details};if(existing)Object.assign(existing,payload);else state.history.unshift(payload);save();renderAll();$('#summarySubtitle').textContent=p.optional?'可选训练完成，恢复同样重要。':'主训练完成，本周进度已更新。';$('#summaryMinutes').textContent=minutes;$('#summaryExercises').textContent=p.exercises.length;$('#summarySets').textContent=sets;openSheet('summarySheet')}
function renderPlan(){const e=$('#planList');e.innerHTML='';plan.forEach((p,i)=>{const s=dayState(i),b=document.createElement('button');b.className='plan-card';b.innerHTML=`<div class="plan-day ${s.done?'is-done':''}">${p.short}</div><div><p>${p.day}</p><h3>${p.title}</h3><span>${p.rest?'休息日':(p.optional?'可选训练 · ':'主训练 · ')+p.exercises.length+' 个动作 · '+p.minutes+' 分钟'}</span></div><b>编辑</b>`;b.onclick=()=>openPlanEditor(i);e.appendChild(b)})}
function openPlanEditor(i){editingDay=i;const p=plan[i];$('#planSheetTitle').textContent=`编辑 ${p.day}`;$('#editPlanTitle').value=p.title;$('#editPlanMinutes').value=p.minutes||0;$('#editPlanRest').checked=!!p.rest;$('#editPlanOptional').checked=!!p.optional;renderEditExerciseList();openSheet('planSheet')}function renderEditExerciseList(){const e=$('#editExerciseList'),p=plan[editingDay];e.innerHTML='';if(!p.exercises.length)e.innerHTML='<div class="guide-box">暂无动作。可以点击“+ 动作”添加。</div>';p.exercises.forEach((x,i)=>{const r=document.createElement('div');r.className='edit-ex-row';r.innerHTML=`<div><h4>${x.icon||'🏋️'} ${x.name}</h4><p>${x.sets} 组 × ${x.reps}${x.unit?' '+x.unit:` · ${x.weight||0} kg`}</p></div><button class="delete-ex">删除</button>`;r.querySelector('button').onclick=()=>{p.exercises.splice(i,1);renderEditExerciseList()};e.appendChild(r)})}
function renderCalendar(){const y=calendarCursor.getFullYear(),m=calendarCursor.getMonth();$('#calendarTitle').textContent=`${y}年${m+1}月打卡`;const first=new Date(y,m,1),days=new Date(y,m+1,0).getDate(),off=(first.getDay()+6)%7,g=$('#calendarGrid');g.innerHTML='';for(let i=0;i<off;i++){const x=document.createElement('span');x.className='calendar-day empty';g.appendChild(x)}for(let d=1;d<=days;d++){const date=isoDate(new Date(y,m,d)),h=state.history.find(x=>x.date===date),x=document.createElement('span');x.className='calendar-day'+(date===isoDate()?' today':'')+(h?' hit':'')+(h?.optional?' optional-hit':'');x.textContent=d;g.appendChild(x)}}
function renderPRs(){const map={};state.history.forEach(h=>(h.details||[]).forEach(ex=>(ex.sets||[]).forEach(s=>{if((+s.weight||0)<=0)return;const cur=map[ex.name];if(!cur||+s.weight>+cur.weight||(+s.weight===+cur.weight&&+s.reps>+cur.reps))map[ex.name]={weight:+s.weight,reps:+s.reps,date:h.date}})));const arr=Object.entries(map).sort((a,b)=>b[1].weight-a[1].weight).slice(0,8),e=$('#prList');e.innerHTML=arr.length?'':'<div class="guide-box">完成带重量的动作后，这里会自动生成 PR。</div>';arr.forEach(([name,r])=>{const c=document.createElement('div');c.className='pr-card';c.innerHTML=`<div><h4>${name}</h4><p>${r.date} · 最佳完成重量</p></div><strong>${r.weight} kg × ${r.reps}</strong>`;e.appendChild(c)})}
function renderRecords(){const hs=state.history,m=isoDate().slice(0,7),mh=hs.filter(h=>h.date.slice(0,7)===m);$('#totalSessions').textContent=hs.length;$('#totalMinutes').textContent=hs.reduce((n,h)=>n+(h.minutes||0),0);$('#monthVolume').textContent=mh.reduce((n,h)=>n+(h.volume||0),0).toLocaleString()+' kg';$('#monthSets').textContent=mh.reduce((n,h)=>n+(h.sets||0),0);$('#historyCount').textContent=`${hs.length} 条`;renderPRs();renderCalendar();const l=$('#historyList');l.innerHTML='';if(!hs.length)l.innerHTML='<div class="guide-box">还没有训练记录。</div>';hs.slice(0,50).forEach(h=>{const d=document.createElement('div');d.className='history-card';d.innerHTML=`<div class="history-date"><strong>${h.date.slice(8)}</strong><span>${h.date.slice(5,7)}月</span></div><div><h4>${h.title}</h4><p>${h.exercises} 动作 · ${h.sets||0} 组 · ${h.minutes} 分钟${h.volume?` · ${h.volume.toLocaleString()} kg`:''}</p></div><span class="history-check">✓</span>`;l.appendChild(d)});drawWeightChart()}
function drawWeightChart(){const c=$('#weightChart'),e=$('#emptyChart'),data=state.weights.slice(-12);if(data.length<2){c.style.display='none';e.style.display='grid';return}c.style.display='block';e.style.display='none';const r=devicePixelRatio||1,w=c.clientWidth||320,h=170;c.width=w*r;c.height=h*r;const x=c.getContext('2d');x.scale(r,r);x.clearRect(0,0,w,h);const vals=data.map(v=>v.value),min=Math.min(...vals)-1,max=Math.max(...vals)+1,p=22;x.strokeStyle='rgba(255,255,255,.08)';for(let i=0;i<4;i++){const y=p+(h-p*2)*i/3;x.beginPath();x.moveTo(p,y);x.lineTo(w-p,y);x.stroke()}const pts=data.map((v,i)=>({x:p+(w-p*2)*i/(data.length-1),y:p+(h-p*2)*(1-(v.value-min)/(max-min))}));x.strokeStyle='#b7ff3c';x.lineWidth=3;x.beginPath();pts.forEach((q,i)=>i?x.lineTo(q.x,q.y):x.moveTo(q.x,q.y));x.stroke();x.fillStyle='#b7ff3c';pts.forEach(q=>{x.beginPath();x.arc(q.x,q.y,4,0,Math.PI*2);x.fill()})}
function renderProfile(){const p=state.profile,name=p.name||'Eggo';$('#profileName').textContent=name;$('#profileGoalText').textContent=`目标：${p.goal}`;$('#profileAvatar').textContent=$('#avatarInitial').textContent=name[0].toUpperCase();$('#nameInput').value=name;$('#goalInput').value=p.goal;$('#weeklyTargetInput').value=p.weeklyTarget;$('#restSecondsInput').value=p.restSeconds;$('#heightInput').value=p.height;$('#targetWeightInput').value=p.targetWeight;const cur=state.weights.at(-1)?.value,h=+p.height/100,t=+p.targetWeight;if(cur&&h){const bmi=cur/(h*h);$('#bmiValue').textContent=bmi.toFixed(1);$('#bmiLabel').textContent=bmi<18.5?'偏轻':bmi<24?'正常范围':bmi<28?'偏高':'较高'}else{$('#bmiValue').textContent='--';$('#bmiLabel').textContent='记录后计算'}if(cur&&t){const gap=Math.abs(cur-t);$('#weightGap').textContent=gap.toFixed(1)+' kg';$('#weightProgressText').textContent=cur>t?`还需减少 ${gap.toFixed(1)} kg`:cur<t?`还需增加 ${gap.toFixed(1)} kg`:'已达到目标'}else{$('#weightGap').textContent='--';$('#weightProgressText').textContent='设置目标体重'}}
function renderAll(){renderHome();renderPlan();renderRecords();renderProfile()}function switchPage(n){$$('.page').forEach(p=>p.classList.toggle('active',p.dataset.page===n));$$('.nav-item').forEach(b=>b.classList.toggle('active',b.dataset.nav===n));$('#pageTitle').textContent={home:'Weekly Fit',plan:'训练计划',records:'数据记录',profile:'我的'}[n];if(n==='records')setTimeout(renderRecords,0)}function openSheet(id){$('#'+id).classList.add('open');document.body.classList.add('modal-open')}function closeSheet(id){$('#'+id).classList.remove('open');if(!$('.sheet-backdrop.open'))document.body.classList.remove('modal-open')}
function renderRestClock(){$('#restClock').textContent=formatClock(restRemaining)}function startRestTimer(sec=null,auto=false){if(sec)restInitial=restRemaining=sec;clearInterval(restTimer);restTimer=null;renderRestClock();openSheet('timerSheet');if(auto)toggleRestTimer(true)}function toggleRestTimer(force=false){if(restTimer&&!force){clearInterval(restTimer);restTimer=null;$('#timerToggleBtn').textContent='继续';return}if(restRemaining<=0)restRemaining=restInitial;$('#timerToggleBtn').textContent='暂停';restTimer=setInterval(()=>{restRemaining--;renderRestClock();if(restRemaining<=0){clearInterval(restTimer);restTimer=null;$('#timerToggleBtn').textContent='重新开始';navigator.vibrate?.([150,100,150]);showToast('休息结束')}} ,1000)}
$('#completeDayBtn').onclick=()=>completeSelectedDay(true);$('#startWorkoutBtn').onclick=startSession;$('#finishSessionBtn').onclick=()=>finishSession(true);$('#openRestTimerBtn').onclick=()=>startRestTimer(+state.profile.restSeconds||90);$('#timerToggleBtn').onclick=()=>toggleRestTimer();$('#timerResetBtn').onclick=()=>{clearInterval(restTimer);restTimer=null;restRemaining=restInitial;renderRestClock();$('#timerToggleBtn').textContent='开始'};$$('[data-rest]').forEach(b=>b.onclick=()=>{restInitial=restRemaining=+b.dataset.rest;clearInterval(restTimer);restTimer=null;renderRestClock();$('#timerToggleBtn').textContent='开始'});
$('#saveExerciseBtn').onclick=()=>{const {dayIdx,exIdx}=activeExercise,s=dayState(dayIdx),rows=updateRows();s.exercises[exIdx]={sets:rows,done:rows.length>0&&rows.every(r=>r.done)};save();closeSheet('exerciseSheet');renderHome();showToast('动作已保存')};$('#addSetBtn').onclick=()=>{const ex=plan[activeExercise.dayIdx].exercises[activeExercise.exIdx],rows=updateRows();rows.push({weight:rows.at(-1)?.weight??ex.weight??0,reps:ex.reps||10,done:false});renderSetRows(rows,ex)};
$('#addWeightBtn').onclick=()=>{ $('#weightInput').value=state.weights.at(-1)?.value||'';openSheet('weightSheet')};$('#saveWeightBtn').onclick=()=>{const v=+$('#weightInput').value;if(v<30||v>250)return showToast('请输入有效体重');const date=isoDate(),x=state.weights.find(a=>a.date===date);x?x.value=v:state.weights.push({date,value:v});state.weights.sort((a,b)=>a.date.localeCompare(b.date));save();closeSheet('weightSheet');renderRecords();renderProfile();showToast('体重已记录')};
$('#saveProfileBtn').onclick=()=>{state.profile={...state.profile,name:$('#nameInput').value.trim()||'Eggo',goal:$('#goalInput').value,weeklyTarget:+$('#weeklyTargetInput').value,restSeconds:+$('#restSecondsInput').value,height:$('#heightInput').value,targetWeight:$('#targetWeightInput').value};save();renderProfile();renderStats();showToast('个人资料已保存')};
$('#addExerciseBtn').onclick=()=>{['newExName','newExTip'].forEach(id=>$('#'+id).value='');$('#newExIcon').value='🏋️';$('#newExSets').value=4;$('#newExReps').value=10;$('#newExWeight').value=0;openSheet('addExerciseSheet')};$('#confirmAddExerciseBtn').onclick=()=>{const name=$('#newExName').value.trim();if(!name)return showToast('请输入动作名称');plan[editingDay].exercises.push({name,icon:$('#newExIcon').value||'🏋️',sets:Math.max(1,+$('#newExSets').value||1),reps:Math.max(1,+$('#newExReps').value||1),weight:Math.max(0,+$('#newExWeight').value||0),tip:$('#newExTip').value.trim()});closeSheet('addExerciseSheet');renderEditExerciseList();showToast('动作已添加')};$('#savePlanBtn').onclick=()=>{const p=plan[editingDay];p.title=$('#editPlanTitle').value.trim()||p.day+'训练';p.minutes=Math.max(0,+$('#editPlanMinutes').value||0);p.rest=$('#editPlanRest').checked;p.optional=!p.rest&&$('#editPlanOptional').checked;if(p.rest)p.exercises=[];save();closeSheet('planSheet');renderAll();showToast('训练计划已更新')};$('#resetPlanBtn').onclick=()=>{if(confirm('恢复默认训练计划？历史训练记录不会删除。')){plan=clone(DEFAULT_PLAN);state.plan=plan;save();renderAll();showToast('已恢复默认计划')}};
$('#resetBtn').onclick=()=>{if(confirm('确定清空全部训练、体重、计划和个人资料吗？')){localStorage.removeItem(KEY);OLD_KEYS.forEach(k=>localStorage.removeItem(k));state=defaults();plan=state.plan;save();renderAll();showToast('全部数据已清空')}};$('#prevMonthBtn').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()-1,1);renderCalendar()};$('#nextMonthBtn').onclick=()=>{calendarCursor=new Date(calendarCursor.getFullYear(),calendarCursor.getMonth()+1,1);renderCalendar()};$('#profileShortcut').onclick=()=>switchPage('profile');$$('.nav-item').forEach(b=>b.onclick=()=>switchPage(b.dataset.nav));$$('[data-close]').forEach(b=>b.onclick=()=>closeSheet(b.dataset.close));$$('.sheet-backdrop').forEach(bg=>bg.addEventListener('click',e=>{if(e.target===bg)closeSheet(bg.id)}));
$('#todayLabel').textContent=`${now.getMonth()+1}月${now.getDate()}日 · ${plan[selected].day}`;restInitial=restRemaining=+state.profile.restSeconds||90;renderAll();renderRestClock();window.addEventListener('resize',()=>{$('.page[data-page="records"]').classList.contains('active')&&drawWeightChart()});if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./service-worker.js'));
